auth_enabled: false

server:
  http_listen_port: 3200

multitenancy_enabled: true

###############################################################################
# 1. OTLP 수신
###############################################################################
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

###############################################################################
# 2. Ingester
###############################################################################
ingester:
  trace_idle_period: 30s
  max_block_duration: 10m
  max_block_bytes: 268435456

###############################################################################
# 3. Compactor - 보존 7일
###############################################################################
compactor:
  compaction:
    block_retention: 168h

###############################################################################
# 4. S3 스토리지
###############################################################################
storage:
  trace:
    backend: s3
    s3:
      bucket: ${TEMPO_S3_BUCKET}
      region: ${AWS_REGION}
      endpoint: s3.${AWS_REGION}.amazonaws.com
      prefix: ftt-tempo/
      storage_class: STANDARD_IA

###############################################################################
# 5. Metrics-generator (span-metrics & service-graphs)
###############################################################################
metrics_generator:
  storage:
    path: /var/tempo/generator-wal
    remote_write:
      - url: http://mimir.lgtm.local:8080/api/v1/push
        send_exemplars: true

###############################################################################
# 6. overrides - 프로세서 켜기
###############################################################################
overrides:
  defaults:
    metrics_generator:
      processors: [span-metrics, service-graphs]

###############################################################################
# 7. 쿼리 동시성
###############################################################################
query_frontend:
  max_outstanding_per_tenant: 64

querier:
  max_concurrent_queries: 16
