services:
  tempo:
    image: grafana/tempo:latest
    user: root
    container_name: ftt-tempo
    restart: unless-stopped
    ports:
      - 3200:3200        # HTTP API
      - 4317:4317        # OTLP gRPC
      - 4318:4318        # OTLP HTTP
    volumes:
      - ./config/tempo-config.yaml:/etc/tempo/tempo.yaml:ro
      - ./tempo-data:/var/tempo
    command:
      - "-config.file=/etc/tempo/tempo.yaml"
    networks:
      - mimir-net        # ← 여기 조인

networks:
  mimir-net:
    external: true       # 이미 존재하는 네트워크 사용